FSDP.UI/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FSDP.Data;
using Microsoft.AspNet.Identity;

namespace FSDP.UI.Controllers
{
    [Authorize]
    public class CoursesController : Controller
    {
        private fsdpEntities db = new fsdpEntities();
        UnitOfWork uow = new UnitOfWork();

        // GET: Courses
        public ActionResult Index()
        {
            var courses1 = db.Courses1.Include(c => c.CourseCategory);
            return View(courses1.ToList());
        }

        //GET: MY Courses - show list of courses where a lesson has been viewed by current user


        // GET: Courses/Details/5
        public ActionResult Details(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
                        
            Course course = db.Courses1.Find(id);
            string userId = User.Identity.GetUserId();
            
            ViewBag.completionPct = uow.CourseRepository.GetCompletionPercentage(course.CourseID, userId);

            var viewedLessons = from c in db.Courses1
                                join l in db.Lessons on c.CourseID equals l.CourseID
                                join lv in db.LessonViews on l.LessonID equals lv.LessonID
                                where c.IsActive == true
                                where l.IsActive == true
                                where l.CourseID == id
                                where lv.UserID == userId
                                where l.LessonViews.Count > 0
                                select c;


            ViewBag.CourseCount = viewedLessons.Count();
           
            return View(course);

        }

        // GET: Courses/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            ViewBag.CategoryID = new SelectList(db.CourseCategories, "CategoryID", "Name");
            return View();
        }

        // POST: Courses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CourseID,Name,Description,IsActive,CategoryID,CourseImage")] Course course)
        {
            if (ModelState.IsValid)
            {
                db.Courses1.Add(course);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryID = new SelectList(db.CourseCategories, "CategoryID", "Name", course.CategoryID);
            return View(course);
        }

        // GET: Courses/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses1.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryID = new SelectList(db.CourseCategories, "CategoryID", "Name", course.CategoryID);
            return View(course);
        }

        // POST: Courses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CourseID,Name,Description,IsActive,CategoryID,CourseImage")] Course course)
        {
            if (ModelState.IsValid)
            {
                db.Entry(course).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryID = new SelectList(db.CourseCategories, "CategoryID", "Name", course.CategoryID);
            return View(course);
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public JsonResult AjaxPublish(int id)
        {
            Course course = db.Courses1.Find(id);
            //update IsActive to true aka "publish"
            course.IsActive = true;
            db.Entry(course).State = EntityState.Modified;
            db.SaveChanges();

            //provide a means to confirm action complete back to user
            var message = string.Format("{0} is now published", course.Name);

            //return Json data for broswer to use to manipulate the page it's already on.
            //Here: creating JS properties with values
            //id of course and confirmation message
            return Json(new { id = id, message = message });
        }

        [Authorize(Roles = "Admin")]
        [AcceptVerbs(HttpVerbs.Post)]
        public JsonResult AjaxUnpublish(int id)
        {
            Course course = db.Courses1.Find(id);
            //update IsActive to false aka "unpublish"
            course.IsActive = false;
            db.Entry(course).State = EntityState.Modified;
            db.SaveChanges();

            //provide a means to confirm action complete back to user
            var message = string.Format("{0} is now unpublished", course.Name);

            //return Json data for broswer to use to manipulate the page it's already on.
            //Here: creating JS properties with values
            //id of course and confirmation message
            return Json(new { id = id, message = message });
        }

        // GET: Courses/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses1.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // POST: Courses/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Course course = db.Courses1.Find(id);
            db.Courses1.Remove(course);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FSDP.UI/Controllers/LessonsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FSDP.Data;
using System.IO;//for file upload
using Microsoft.AspNet.Identity;
using System.Net.Mail;

namespace FSDP.UI.Controllers
{
    [Authorize]
    public class LessonsController : Controller
    {
        private fsdpEntities db = new fsdpEntities();

        // GET: Lessons
        public ActionResult Index()
        {
            var lessons = db.Lessons.Include(l => l.Cours);
            return View(lessons.ToList());
        }


        //public ActionResult Details(int id)
        //{
        //    Lesson lesson = db.Lessons.Where(x => x.LessonID.Equals(id)).FirstOrDefault();

        //    LessonView item = new LessonView();
        //    item.LessonID = id;
        //    item.UserID = User.Identity.GetUserId();
        //    item.DateViewed = DateTime.Now;

        //    var existingView = db.LessonViews
        //        .Where(x => x.LessonID.Equals(item.LessonID))
        //        .Where(x => x.UserID.Equals(item.UserID))
        //        .FirstOrDefault();

        //    //db.Employees.Where(x => x.FirstName.Contains(e.FirstName)).Where(x => x.LastName.Contains(e.LastName)).FirstOrDefault();

        //    if (existingView == null)
        //    {
        //        db.LessonViews.Add(item);
        //        db.SaveChanges();


        //        Course course = db.Courses1.Where(x => x.CourseID.Equals(lesson.CourseID)).FirstOrDefault();
        //        string userId = User.Identity.GetUserId();

        //        var viewedLessons = from c in db.Courses1
        //                            join l in db.Lessons on c.CourseID equals l.CourseID
        //                            join lv in db.LessonViews on l.LessonID equals lv.LessonID
        //                            where c.IsActive == true
        //                            where l.CourseID == id
        //                            where lv.UserID == userId
        //                            where l.LessonViews.Count > 0
        //                            select c;


        //        //Course.Lessons.Count - ViewBag.CourseCount) == 0
        //        if ((course.Lessons.Count - viewedLessons.Count()) == 0)
        //        {
        //            CourseCompletion cc = new CourseCompletion();
        //            cc.CourseID = lesson.CourseID;
        //            cc.UserID = User.Identity.GetUserId();
        //            cc.DateCompleted = DateTime.Now;

        //            var existingCompletion = db.CourseCompletions
        //                                    .Where(x => x.CourseID.Equals(cc.CourseID))
        //                                    .Where(x => x.UserID.Equals(cc.UserID))
        //                                    .FirstOrDefault();


        //            if (existingCompletion == null)
        //            {
        //                //save completion to the database only ONE TIME
        //                db.CourseCompletions.Add(cc);
        //                db.SaveChanges();
        //            }
        //            }

        //    }

        //    return View(lesson);

        //}

        //GET: Lessons/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            string userId = User.Identity.GetUserId();
            Lesson lesson = db.Lessons.Find(id);
            Course course = db.Courses1.Find(lesson.CourseID);
            CourseCompletion completion = new CourseCompletion();
            completion.CourseID = course.CourseID;
            completion.UserID = userId;
            completion.DateCompleted = DateTime.Now;

            var existingView = db.CourseCompletions.Where(x => x.CourseID.Equals(course.CourseID))
                                                   .Where(x => x.UserID.Equals(completion.UserID))
                                                   .FirstOrDefault();


            var viewedLessons = from c in db.Courses1
                                join l in db.Lessons on c.CourseID equals l.CourseID
                                join lv in db.LessonViews on l.LessonID equals lv.LessonID
                                where c.IsActive == true
                                where l.IsActive == true
                                where l.CourseID == course.CourseID
                                where lv.UserID == userId
                                where l.LessonViews.Count > 0
                                select c;

            var activeLessons = course.Lessons.Where(x => x.IsActive == true).Count();
            var courseCount = viewedLessons.Count();
            if (existingView == null)
            {
                if ((activeLessons - courseCount) == 0)
                {
                    db.CourseCompletions.Add(completion);
                    db.SaveChanges();

                    //create the body for the email
                    string subject = Session["FirstName"] + " " + Session["LastName"] + " completed " + course.Name;
                    string message = "All lessons have been viewed";

                    string body = string.Format(
                        "Name: {0}<br/>Email: {1}<br/>Subject: {2}<br/>Message:<br/>{3}",
                        /*User.Identity.Name*/
                        Session["FirstName"],
                        User.Identity.GetUserName(),
                        subject,
                        message
                        );
                    //create and configure the Mail Message
                    MailMessage msg = new MailMessage(
                        "no-reply@mjgarten.net",
                        "mjgartendev@gmail.com",
                        subject,
                        body
                        );

                    //configure the Mail Message object
                    msg.IsBodyHtml = true;

                    //create and configure the SMTP client
                    SmtpClient client = new SmtpClient(
                        "mail.mjgarten.net");
                    client.Credentials = new NetworkCredential("no-reply@mjgarten.net", "noreply32!");

                    using (client)
                    {
                        try
                        {
                            client.Send(msg);
                        }
                        catch
                        {
                            ViewBag.ErrorMessage = "There was an error sending your email. Please try again.";
                            return View();
                        };
                    }
                }
            }


            ViewBag.CourseName = course.Name;
            ViewBag.TotalLessons = activeLessons;
            ViewBag.CourseCount = viewedLessons.Count();

            //Youtube video player stuff
            if (lesson.VideoURL != null)
            {


                string CompleteYouTubeURL = lesson.VideoURL;

                var v = CompleteYouTubeURL.IndexOf("v=");
                var amp = CompleteYouTubeURL.IndexOf("&", v);
                string vid;
                // if the video id is the last value in the url
                if (amp == -1)
                {
                    vid = CompleteYouTubeURL.Substring(v + 2);
                    // if there are other parameters after the video id in the url
                }
                else
                {
                    vid = CompleteYouTubeURL.Substring(v + 2, amp - (v + 2));
                }
                ViewBag.VideoURL = vid;
            }



            if (lesson == null)
            {
                return HttpNotFound();
            }
            return View(lesson);
        }

        // GET: Lessons/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            ViewBag.CourseID = new SelectList(db.Courses1, "CourseID", "Name");
            return View();
        }

        // POST: Lessons/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "LessonID,Title,CourseID,Introduction,VideoURL,PdfFilename,IsActive")] Lesson lesson, HttpPostedFileBase PdfFilename)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    string fileName = "";
                    if (PdfFilename != null)
                    {
                        //string pdfExt = Path.GetExtension(PdfFilename.FileName).ToLower();
                        //string[] allowedExtensions = { ".pdf", ".docx" };
                        //if (allowedExtensions.Contains(pdfExt)
                        //{

                        //save file to the server
                        fileName = Path.GetFileName(PdfFilename.FileName);
                        string savePath = Server.MapPath("~/Content/Files/");
                        PdfFilename.SaveAs(savePath + fileName);
                        //}
                    }
                    //save filename to Database
                    lesson.PdfFilename = fileName;
                }
                catch (Exception)
                {

                    throw;
                }

                //Youtube URL upload thing
                //var v = lesson.VideoURL.IndexOf("v=");
                //var amp = lesson.VideoURL.IndexOf("&", v);
                //string vid;
                //// if the video id is the last value in the url
                //if (amp == -1)
                //{
                //    vid = lesson.VideoURL.Substring(v + 2);

FSDP.UI/Views/Lessons/Create.cshtml
@model FSDP.Data.Lesson

@{
    ViewBag.Title = "Add New Lesson";
}

<h2>Add New Lesson</h2>

@using (Html.BeginForm("Create", "Lessons", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CourseID, "CourseID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CourseID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CourseID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Introduction, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Introduction, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Introduction, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VideoURL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VideoURL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VideoURL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PdfFilename, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="PdfFilename" id="PdfFilename" />
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.PdfFilename, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PdfFilename, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PdfFilename, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsActive)
                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FSDP.UI/Views/Lessons/Delete.cshtml
@model FSDP.Data.Lesson

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Lesson</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Introduction)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Introduction)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VideoURL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VideoURL)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PdfFilename)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PdfFilename)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cours.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cours.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

FSDP.UI/Views/Lessons/Details.cshtml
@model FSDP.Data.Lesson

@{
    ViewBag.Title = Model.Title + " Details";
    if (ViewBag.CourseCount > 0 && ViewBag.TotalLessons > 0)
    {
        ViewBag.PctComplete = (ViewBag.CourseCount * 100 / ViewBag.TotalLessons);
    }
    else
    {
        ViewBag.PctComplete = 0;
    }
}

<p class="lead"><span class="text-muted">Course:</span>  <strong>@ViewBag.CourseName</strong> <span class="text-muted pull-right">@ViewBag.CourseCount/@ViewBag.TotalLessons Lessons Completed</span></p>
<div class="progress">
    <div class="progress-bar progress-bar-success progress-bar-striped active" role="progressbar" aria-valuenow="@ViewBag.PctComplete" aria-valuemin="0" aria-valuemax="100" style="width: @ViewBag.PctComplete%">
        <span class="sr-only">@ViewBag.PctComplete% Complete</span>
    </div>
</div>
<hr />

<div class="col-md-8 col-md-offset-2 text-center">
    <h1 class="success"> <strong>@Model.Title</strong></h1>
    <p class="lead">
        @Html.DisplayFor(model => model.Introduction)
    </p>
    <hr />
    PDF Link:
    @if (Model.PdfFilename == "")
    {
        <p>There is no PDF for this lesson</p>
    }
    else
    {
      <a href="~/Content/Files/@Model.PdfFilename" target="_blank"> @Model.PdfFilename</a>
    }
    <br />
    <br />
</div>

<div class="col-md-12 text-center">
    @if (Model.VideoURL != null)
    {
        <div id="player"></div>
    }
    else
    {
        <h2 class="jumbotron text-center">
            There is no video for this lesson
        </h2>
    }
    <br />
    
</div>

<div class="col-md-8 col-md-offset-2">
    <hr />

    <p class="text-center">
        <a class="btn btn-success" href="@Url.Action("Details", "Courses", new { id = Model.CourseID })">Complete Lesson</a>
    </p>
</div>

@section scripts{
    
    <script src="http://www.youtube.com/player_api"></script>

<script>
// create youtube player
var player;
var h = '@ViewBag.height';
var w = '@ViewBag.width';
function onYouTubePlayerAPIReady() {
player = new YT.Player('player', {
height: 360,
width: 640,
modestbranding: 1,
videoId: '@ViewBag.VideoURL',
playerVars: {
rel: 0,
autoplay: 0,
disablekb: 0,
showsearch: 0,
showinfo: 0,
controls: 1,
fs: 1,
hd: 1,
html5: 1,
iv_load_policy: 3
},
events: {
onReady: onPlayerReady,
onStateChange: onPlayerStateChange
}
});
}
// autoplay video
function onPlayerReady(event) {
event.target.playVideo();
}

// when video ends
function onPlayerStateChange(event) {
if(event.data === 0) {
//do something on end;
alert('done');
}
}
</script>
    }

FSDP.UI/Views/Lessons/Index.cshtml
@model IEnumerable<FSDP.Data.Lesson>

@{
    ViewBag.Title = "All Lessons";
}

<h2>Lessons</h2>

@if (User.IsInRole("Admin"))
{

    <p>
        @Html.ActionLink("Create New", "Create")
    </p>

    <ul class="nav nav-tabs">
        <li class="active"><a data-toggle="tab" href="#home">Active </a></li>
        <li><a data-toggle="tab" href="#menu2">Inactive </a></li>
    </ul>
}

<div class="tab-content">
    <br />
    <div id="home" class="tab-pane fade in active">
        <br />
        <table class="table" id="activeTable">
            <thead>
                <tr>
                    @if (User.IsInRole("Admin"))
                    {
                        <th></th>
                        <th></th>
                    }
                    <th>
                        @Html.DisplayNameFor(model => model.Title)
                    </th>
                    <th>
                        Course
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Introduction)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.PdfFilename)
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Where(x => x.IsActive == true))
                {
                    <tr id="ActiveLesson-@item.LessonID">
                        @if (User.IsInRole("Admin"))
                        {
                            <td>
                                @Ajax.ActionLink("Unpublish", "AjaxUnpublish", "Lessons", new { id = item.LessonID },
                            new AjaxOptions
                            {
                                HttpMethod = "POST",
                                OnSuccess = "unpublishConfirmed"
                            })
                            </td>
                                <td>
                                    <a href="@Url.Action("Edit", "Lessons", new { id = item.LessonID })">Edit</a>
                                </td>
                        }
                        <td>
                            <a href="@Url.Action("Details", "Lessons", new { id = item.LessonID })">
                                @Html.DisplayFor(modelItem => item.Title)
                            </a>
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Cours.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Introduction)
                        </td>
                        <td>
                            <a href="~/Content/Files/@item.PdfFilename" target="_blank">@item.PdfFilename</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    @if (User.IsInRole("Admin"))
    {
        <div id="menu2" class="tab-pane fade in">
            <br />
            <table class="table" id="inactiveTable">
                <thead>
                    <tr>
                        @if (User.IsInRole("Admin"))
                        {
                            <th></th>
                                <th></th>
                        }
                        <th>
                            @Html.DisplayNameFor(model => model.Title)
                        </th>
                        <th>
                            Course
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Introduction)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.PdfFilename)
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Where(x => x.IsActive == false))
                    {
                        <tr id="Lesson-@item.LessonID">
                            @if (User.IsInRole("Admin"))
                            {
                                <td>
                                    @Ajax.ActionLink("Publish", "AjaxPublish", "Lessons", new { id = item.LessonID },
new AjaxOptions
{
    HttpMethod = "POST",
    OnSuccess = "publishConfirmed"
})
                                </td>
                                    <td>
                                        <a href="@Url.Action("Edit", "Lessons", new { id = item.LessonID })">Edit</a>
                                    </td>
                            }
                            <td>
                                <a href="@Url.Action("Details", "Lessons", new { id = item.LessonID })">
                                    @Html.DisplayFor(modelItem => item.Title)
                                </a>
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Cours.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Introduction)
                            </td>
                            <td>
                                <a href="~/Content/Files/@item.PdfFilename" target="_blank">@item.PdfFilename</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    }
</div>

@section scripts{
    <script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js" type="text/javascript"></script>
    <script>
        $(document).ready(function () {
            $('#activeTable').DataTable();
            $('#inactiveTable').DataTable();
        });
    </script>

    <script>
        //----Ajax Publish Confirmation----
        function publishConfirmed(response, status, data) {
            //remove the row from the table
            var rowId = "#Lesson-" + response.id;
            var row = $('#inactiveTable').find(rowId);
            $('#activeTable').append(row);
            $('#inactiveTable').find(rowId).remove();

            //display a status message
            $('#MessageContent').html("<div class='alert alert-dismissable alert-success'>" + response.message + "</div>");
        }

        function unpublishConfirmed(response, status, data) {
            //remove the row from the table
            var rowId = "#ActiveLesson-" + response.id;
            var row = $('#activeTable').find(rowId);
            $('#inactiveTable').append(row);
            $('#activeTable').find(rowId).remove();

            //display a status message
            $('#MessageContent').html("<div class='alert alert-dismissable alert-success'>" + response.message + "</div>");
        }
    </script>
}