FSDP.UI/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FSDP.Data;
using Microsoft.AspNet.Identity;

namespace FSDP.UI.Controllers
{
    [Authorize]
    public class CoursesController : Controller
    {
        private fsdpEntities db = new fsdpEntities();
        UnitOfWork uow = new UnitOfWork();

        // GET: Courses
        public ActionResult Index()
        {
            var courses1 = db.Courses1.Include(c => c.CourseCategory);
            return View(courses1.ToList());
        }

        //GET: MY Courses - show list of courses where a lesson has been viewed by current user


        // GET: Courses/Details/5
        public ActionResult Details(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
                        
            Course course = db.Courses1.Find(id);
            string userId = User.Identity.GetUserId();
            
            ViewBag.completionPct = uow.CourseRepository.GetCompletionPercentage(course.CourseID, userId);

            var viewedLessons = from c in db.Courses1
                                join l in db.Lessons on c.CourseID equals l.CourseID
                                join lv in db.LessonViews on l.LessonID equals lv.LessonID
                                where c.IsActive == true
                                where l.IsActive == true
                                where l.CourseID == id
                                where lv.UserID == userId
                                where l.LessonViews.Count > 0
                                select c;


            ViewBag.CourseCount = viewedLessons.Count();
           
            return View(course);

        }

        // GET: Courses/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            ViewBag.CategoryID = new SelectList(db.CourseCategories, "CategoryID", "Name");
            return View();
        }

        // POST: Courses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CourseID,Name,Description,IsActive,CategoryID,CourseImage")] Course course)
        {
            if (ModelState.IsValid)
            {
                db.Courses1.Add(course);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryID = new SelectList(db.CourseCategories, "CategoryID", "Name", course.CategoryID);
            return View(course);
        }

        // GET: Courses/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses1.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryID = new SelectList(db.CourseCategories, "CategoryID", "Name", course.CategoryID);
            return View(course);
        }

        // POST: Courses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CourseID,Name,Description,IsActive,CategoryID,CourseImage")] Course course)
        {
            if (ModelState.IsValid)
            {
                db.Entry(course).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryID = new SelectList(db.CourseCategories, "CategoryID", "Name", course.CategoryID);
            return View(course);
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public JsonResult AjaxPublish(int id)
        {
            Course course = db.Courses1.Find(id);
            //update IsActive to true aka "publish"
            course.IsActive = true;
            db.Entry(course).State = EntityState.Modified;
            db.SaveChanges();

            //provide a means to confirm action complete back to user
            var message = string.Format("{0} is now published", course.Name);

            //return Json data for broswer to use to manipulate the page it's already on.
            //Here: creating JS properties with values
            //id of course and confirmation message
            return Json(new { id = id, message = message });
        }

        [Authorize(Roles = "Admin")]
        [AcceptVerbs(HttpVerbs.Post)]
        public JsonResult AjaxUnpublish(int id)
        {
            Course course = db.Courses1.Find(id);
            //update IsActive to false aka "unpublish"
            course.IsActive = false;
            db.Entry(course).State = EntityState.Modified;
            db.SaveChanges();

            //provide a means to confirm action complete back to user
            var message = string.Format("{0} is now unpublished", course.Name);

            //return Json data for broswer to use to manipulate the page it's already on.
            //Here: creating JS properties with values
            //id of course and confirmation message
            return Json(new { id = id, message = message });
        }

        // GET: Courses/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses1.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // POST: Courses/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Course course = db.Courses1.Find(id);
            db.Courses1.Remove(course);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FSDP.UI/Controllers/LessonViewsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FSDP.Data;
using Microsoft.AspNet.Identity;
using System.Web.Mail;
using System.Net.Mail;

namespace FSDP.UI.Controllers
{
    //[Authorize]
    public class LessonViewsController : Controller
    {
        private fsdpEntities db = new fsdpEntities();
        UnitOfWork uow = new UnitOfWork();

        // GET: LessonViews
        public ActionResult Index()
        {
            string user = User.Identity.GetUserId();
            var lessonViews = db.LessonViews.Where(x => x.UserID.Equals(user)).Include(l => l.Lesson);
            return View(lessonViews.ToList());
        }

        //GET: LessonViews only for current User
        [Authorize(Roles ="Admin, Manager")]
        public ActionResult ManagerView(string id)
        {
            var lessonViews = db.LessonViews.Where(u => u.AspNetUser.FirstName.Contains(id)).Include(l => l.Lesson).Include(u => u.AspNetUser);

            return View(lessonViews.ToList());
        }

        // GET: LessonViews/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LessonView lessonView = db.LessonViews.Find(id);
            if (lessonView == null)
            {
                return HttpNotFound();
            }
            return View(lessonView);
        }

        [AllowAnonymous]
        public ActionResult Add(int id)
        {
            LessonView item = new LessonView();
            item.LessonID = id;
            item.UserID = User.Identity.GetUserId();
            item.DateViewed = DateTime.Now;

            var existingView = db.LessonViews
                .Where(x => x.LessonID.Equals(item.LessonID))
                .Where(x => x.UserID.Equals(item.UserID))
                .FirstOrDefault();

           
            //db.Employees.Where(x => x.FirstName.Contains(e.FirstName)).Where(x => x.LastName.Contains(e.LastName)).FirstOrDefault();

            if (existingView == null)
            {
                db.LessonViews.Add(item);
                db.SaveChanges();
            }
                                          
            //TODO: redirect to lesson details view for current LessonID
            return RedirectToAction("Details", "Lessons", new { id = item.LessonID });
        }

        // GET: LessonViews/Create
        public ActionResult Create()
        {
            ViewBag.LessonID = new SelectList(db.Lessons, "LessonID", "Title");
            return View();
        }

        // POST: LessonViews/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "LessonViewID,UserID,LessonID,DateViewed")] LessonView lessonView)
        {
            if (ModelState.IsValid)
            {
                db.LessonViews.Add(lessonView);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.LessonID = new SelectList(db.Lessons, "LessonID", "Title", lessonView.LessonID);
            return View(lessonView);
        }

        // GET: LessonViews/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LessonView lessonView = db.LessonViews.Find(id);
            if (lessonView == null)
            {
                return HttpNotFound();
            }
            ViewBag.LessonID = new SelectList(db.Lessons, "LessonID", "Title", lessonView.LessonID);
            return View(lessonView);
        }

        // POST: LessonViews/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "LessonViewID,UserID,LessonID,DateViewed")] LessonView lessonView)
        {
            if (ModelState.IsValid)
            {
                db.Entry(lessonView).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.LessonID = new SelectList(db.Lessons, "LessonID", "Title", lessonView.LessonID);
            return View(lessonView);
        }

        // GET: LessonViews/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LessonView lessonView = db.LessonViews.Find(id);
            if (lessonView == null)
            {
                return HttpNotFound();
            }
            return View(lessonView);
        }

        // POST: LessonViews/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            LessonView lessonView = db.LessonViews.Find(id);
            db.LessonViews.Remove(lessonView);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FSDP.UI/Views/Courses/Create.cshtml
@model FSDP.Data.Course

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Course</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsActive)
                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryID, "CategoryID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CourseImage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CourseImage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CourseImage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FSDP.UI/Views/Courses/Delete.cshtml
@model FSDP.Data.Course

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Course</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CourseImage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CourseImage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CourseCategory.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CourseCategory.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

FSDP.UI/Views/Courses/Details.cshtml
@model FSDP.Data.Course
@using Microsoft.AspNet.Identity;

@{
    ViewBag.Title = "Details";
    var userId = User.Identity.GetUserId();
    if (ViewBag.CourseCount > 0 && Model.Lessons.Where(l => l.IsActive == true).Count() > 0)
    {
        ViewBag.PctComplete = (ViewBag.CourseCount * 100 / Model.Lessons.Where(l => l.IsActive == true).Count());
    }
    else
    {
        ViewBag.PctComplete = 0;
    }
}

<p class="lead"><span class="text-muted">Course:</span> <strong>@Model.Name </strong><span class="text-muted pull-right">@ViewBag.CourseCount/@Model.Lessons.Where(l => l.IsActive == true).Count() Lessons Completed</span></p>
<div class="progress">
    <div class="progress-bar progress-bar-success progress-bar-striped active" role="progressbar" aria-valuenow="@ViewBag.PctComplete" aria-valuemin="0" aria-valuemax="100" style="width: @ViewBag.PctComplete%">
        <span class="sr-only">@ViewBag.PctComplete% Complete</span>
    </div>
</div>
<hr />
<p>Method Test: @ViewBag.completionPct</p>

<a href="@Url.Action("Index", "Home")" class="btn btn-default"><i class="glyphicon glyphicon-arrow-left"></i></a>
@if (User.IsInRole("Admin"))
{
<a href="@Url.Action("Edit", "Courses", new { id = Model.CourseID })" class="btn btn-info"><i class="glyphicon glyphicon-pencil"></i></a>
}
<br />
<div class="row">
    <div class="text-center col-md-8 col-md-offset-2">

        <p class="text-muted">
            Category: @Html.DisplayFor(model => model.CourseCategory.Name)
        </p>

        <p class="lead">@Html.DisplayFor(model => model.Description)</p>

        @Html.DisplayFor(model => model.CourseImage)

    </div>

    <div class="col-md-8 col-md-offset-2 lesson-container">
        <h3 class="text-center"> Lessons <span class="badge"> @Model.Lessons.Where(x => x.IsActive == true).Count()</span></h3>
        <ul class="list-group">
            @foreach (var item in Model.Lessons.Where(l => l.IsActive == true))
            {

                <a href="@Url.Action("Add", "LessonViews", new { id = item.LessonID })">
                    @if (item.LessonViews.Where(x => x.UserID.Equals(userId)).Count() > 0)
                    {
                        <li class="list-group-item completedLesson">
                            <h4>
                                <i class="glyphicon glyphicon-ok"></i> 
                                 @item.Title
                            </h4>
                            <p class="text-muted text-center">@item.Introduction</p>
                        </li>
                    }
                    else
                    {
                        <li class="list-group-item">
                            <h4>@item.Title</h4>
                            <p class="text-muted text-center">@item.Introduction</p>
                        </li>
                    }

                </a>
            }
        </ul>
    </div>

</div>

FSDP.UI/Views/Courses/Edit.cshtml
@model FSDP.Data.Course

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Course</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CourseID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsActive)
                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryID, "CategoryID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CourseImage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CourseImage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CourseImage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FSDP.UI/Views/Courses/Index.cshtml
@model IEnumerable<FSDP.Data.Course>

@{
    ViewBag.Title = "Courses";
}

<h2>@ViewBag.Title</h2>

@if (User.IsInRole("Admin"))
{
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>

    <ul class="nav nav-tabs">
        <li class="active"><a data-toggle="tab" href="#home">Courses</a></li>
        <li><a data-toggle="tab" href="#menu2">Inactive</a></li>
    </ul>
}

<div class="tab-content">
    <br />
    <div id="home" class="tab-pane fade in active">
        <table class="table" id="activeTable">
            <thead>
                <tr>
                    @if (User.IsInRole("Admin"))
                    {
                    <th></th>
                    <th></th>
                    }
                    <th>
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <th>
                        Category
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Description)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.IsActive)
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Where(x => x.IsActive == true))
            {
                <tr id="ActiveCourse-@item.CourseID">
                    @if (User.IsInRole("Admin"))
                        {
                        <td>
                            @Ajax.ActionLink("Unpublish", "AjaxUnpublish", "Courses", new { id = item.CourseID },
new AjaxOptions
{
    HttpMethod = "POST",
    OnSuccess = "unpublishConfirmed"
})
                        </td>
                        <td>
                            <a href="@Url.Action("Edit", "Courses", new { id = item.CourseID })">Edit</a>
                        </td>
                        }
                    <td>
                        <a href="@Url.Action("Details","Courses", new { id = item.CourseID })">
                            @Html.DisplayFor(modelItem => item.Name)
                        </a>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CourseCategory.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.IsActive)
                    </td>

                </tr>
                }
            </tbody>

        </table>
    </div>

    @if (User.IsInRole("Admin"))
    {
        <div id="menu2" class="tab-pane fade">
            <table class="table" id="inactiveTable">
                <thead>
                    <tr>
                        @if (User.IsInRole("Admin"))
                        {
                            <th></th>
                            <th></th>
                        }
                        <th>
                            @Html.DisplayNameFor(model => model.Name)
                        </th>
                        <th>
                            Category
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Description)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.IsActive)
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Where(m => m.IsActive == false))
                {
                        <tr id="InactiveCourse-@item.CourseID">
                            @if (User.IsInRole("Admin"))
                    {
                                <td>
                                    @Ajax.ActionLink("Publish", "AjaxPublish", "Courses", new { id = item.CourseID },
new AjaxOptions
{
    HttpMethod = "POST",
    OnSuccess = "publishConfirmed"
})
                                </td>
                                <td>
                                    <a href="@Url.Action("Edit", "Courses", new { id = item.CourseID })">Edit</a>
                                </td>
                            }

                            <td>
                                <a href="@Url.Action("Details","Courses")">
                                    @Html.DisplayFor(modelItem => item.Name)
                                </a>
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.CourseCategory.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Description)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.IsActive)
                            </td>

                        </tr>
                    }
                </tbody>
            </table>
        </div>
    }
</div>

@section scripts{
    <script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js" type="text/javascript"></script>
    <script>
        $(document).ready(function () {
            $('#activeTable').DataTable();
            $('#inactiveTable').DataTable();
        });
    </script>

    <script>
        //----Ajax Publish Confirmation----
        function publishConfirmed(response, status, data) {
            //remove the row from the table
            var rowId = "#InactiveCourse-" + response.id;
            var row = $('#inactiveTable').find(rowId);
            $('#activeTable').append(row);
            $('#inactiveTable').find(rowId).remove();

            //display a status message
            $('#MessageContent').html("<div class='alert alert-dismissable alert-success'>" + response.message + "</div>");
        }

        function unpublishConfirmed(response, status, data) {
            //remove the row from the table
            var rowId = "#ActiveCourse-" + response.id;
            var row = $('#activeTable').find(rowId);
            $('#inactiveTable').append(row);
            $('#activeTable').find(rowId).remove();


            //display a status message
            $('#MessageContent').html("<div class='alert alert-dismissable alert-success'>" + response.message + "</div>");
        }
    </script>
}